-- AlterTable
ALTER TABLE `Organization` ADD COLUMN `btAppKeyEnc` TEXT NULL,
    ADD COLUMN `btAppKeyHint` VARCHAR(191) NULL,
    ADD COLUMN `btAppUser` VARCHAR(191) NULL,
    ADD COLUMN `btCodSocio` VARCHAR(191) NULL,
    ADD COLUMN `btCredStatus` ENUM('SIN_LLAVE', 'CARGADA', 'VERIFICADA', 'INVALIDA') NOT NULL DEFAULT 'SIN_LLAVE',
    ADD COLUMN `btCredVerifiedAt` DATETIME(3) NULL;
